name: Publish Docker image

on:
  workflow_dispatch:
    inputs:
      node_version:
        description: 'Node version'
        default: '16-bullseye'
        required: true
        type: string
      n8n_version:
        description: 'N8n version'
        # default: '0.189.1'
        required: true
        type: string

jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: docker/
          push: true
          tags: ruanjf/n8n:${{ inputs.n8n_version }}-${{ inputs.node_version }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          build-args: |
            NODE_VERSION=${{ inputs.node_version }}
            N8N_VERSION=${{ inputs.n8n_version }}

      # - uses: actions/checkout@v3
      # - name: Build the Docker image
      #   run: docker build docker/ --tag ruanjf/n8n:${{ inputs.n8n_version }}-${{ inputs.node_version }} --build-arg N8N_VERSION=${{ inputs.n8n_version }}
