name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file docker/Dockerfile --tag ruanjf/n8n:${{ matrix.n8n_version }}-${{ matrix.node_version }} --build-arg N8N_VERSION=${{ matrix.n8n_version }}
